config/routes.rb
NewsPortal::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  ActiveAdmin.routes(self)
  devise_for :users
  match '/users/unsubscribe/:signature' => 'users#unsubscribe', as: 'unsubscribe', via: 'get'
  root 'posts#category'
  match '/about', to: 'static_pages#about', via: 'get'
  resources :posts do
    get '/category/:slug' => :category, on: :collection, as: 'category'
  end

  resources :subscriptions, only: [:index, :create, :destroy]
  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments]

end

app/models/post.rb
class Post < ActiveRecord::Base
  include TheComments::Commentable
  has_and_belongs_to_many :categories
  belongs_to :user
  validates :user_id,     presence: true
  validates :title,       presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 400 }
  validates :content,     presence: true, length: { maximum: 4000 }

  # "subscription_mailer" fetches the users who need to send a mail
  def subscription_mailer
    users_id = Subscription.where('category_id in (?)', self.categories.ids).distinct.pluck(:user_id)
    users_id.delete(self.user.id)
    if users_id.any?
      number_elements = ((users_id.size/25.to_f).round == 0 ? 1 : (users_id.size/25.to_f).round)
      users_id.each_slice(number_elements) {|array| UserMailer.delay.subscription(array, self.id) }
    end
  end

  # Denormalization methods
  def commentable_title
    "Undefined Post Title"
  end

  def commentable_url
    "#"
  end

  def commentable_state
    "published"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :get_posts, only: [:category, :destroy]
  before_filter :find_post, only: [:edit, :update, :show, :destroy]
  before_filter :get_categories, only: [:new, :create, :edit]
  load_and_authorize_resource except: [:create]

  def category
    render 'posts/index'
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = 'Post successfully created'
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    params[:post][:category_ids] ||= []
    if @post.update_attributes(post_params)
      flash[:success] = 'Post successfully updated!'
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def show
    if @post.approval
      @comments = @post.comments.with_state([:draft, :published])
    else
      render 'posts/not_approved'
    end
  end

  def destroy
    @post.destroy
    flash.now[:success] = 'Post deleted'
    respond_to do |format|
      format.js
    end
  end

  # Before_filters
  def get_posts
    if params[:slug]
      category = Category.find_by(title: params[:slug])
      @posts = category.posts.paginate(page: params[:page]).where('approval = true').order('created_at DESC')
    else
      @posts = Post.paginate(page: params[:page]).where('approval = true').order('created_at DESC')
    end
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def get_categories
    @categories = Category.all
  end

  private
    def post_params
      params.require(:post).permit(:title, :description, :content, :approval, :category_ids => []).merge!(user_id: current_user.id)
    end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/_form.html.slim
#respond.comment-respond
  h3#reply-title.comment-reply-title
  = form_for(@post) do |f|
    = f.label :title
    = f.text_field :title, :autofocus => true

    .field
      = f.text_area :description, placeholder: "Compose description..."
    .field
      = f.text_area :content, :class => "redactor", :rows => 40, :cols => 120, placeholder: "Compose new post..."
    br
    - for category in @categories
      .checkbox
        = check_box_tag "post[category_ids][]", category.id, @post.categories.include?(category)
        = category.title.capitalize
    br
    = f.submit "Post", class: "btn btn-primary"

app/views/posts/_post.html.slim
.row-fluid
  .span12.well
    h3
      = link_to post.title, post_path(post)
    | #{post.description}
    br
    = link_to "Learn more >>", post_path(post), class: "btn btn-mini pull-right"
    - if can? :destroy, post
      = link_to "Destroy", post_path(post, slug: params[:slug]), data: {confirm: 'Are you sure?'}, method: :delete, remote: true

app/views/posts/_sidebar.html.slim
ul.nav.nav-list
  li.nav-header
    h4.center Best post
  li
    = link_to "In auctor mauris non pharetra tempor.", "#"
  li
    = link_to "Sed posuere ipsum in nisi tristique lobortis.", "#"
  li
    = link_to "Mauris eleifend eu diam in placerat. ", "#"
  li
    = link_to "Curabitur adipiscing mauris lorem, et pulvinar enim laoreet ultrices.", "#"
  li
    = link_to "Nulla id dapibus dui.", "#"
  li
    = link_to "Vivamus et lectus lectus.", "#"
  li
    = link_to "Sed gravida eros at semper accumsan.", "#"
  li
    = link_to "Sed ligula ante, consectetur eget erat vel, hendrerit malesuada magna.", "#"
  li
    = link_to "Ut in lectus eget velit ultrices rhoncus.", "#"
  li
    = link_to "Aenean quis justo ornare, consequat lorem sit amet, pharetra orci.", "#"

app/views/posts/destroy.js.erb
$("#posts").html("<%= escape_javascript(render @posts) %>");
$("#flash").html("<%= escape_javascript(render :partial => 'layouts/flash' , :locals => { :flash => flash }) %>");

app/views/posts/edit.html.slim
h1 Edit post
.row-fluid
  .span10.offset1
    = render partial: 'form'

app/views/posts/index.html.slim
.row-fluid
  .span8#posts
    = render @posts
    = will_paginate @posts
  .span4.well.sidebar-nav
    = render 'sidebar'

app/views/posts/new.html.slim
h1 New post
.row-fluid
  .span10.offset1
    = render partial: 'form'

app/views/posts/not_approved.html.slim
.hero-unit
  h2.center This post is in moderation and not yet approved.

app/views/posts/show.html.slim
.hero-unit
  .center
    h3 #{@post.title}
  br
  = raw @post.content
  br
  hr
  | In Categories:
  ul
    - @post.categories.each do |i|
      li = i.title.capitalize
  - if can? :update, @post
    = link_to "Edit", edit_post_path(@post)
  hr
  h3 Comments
  br
  #comments
    = render partial: 'the_comments/tree', locals: { commentable: @post, comments_tree: @comments }