config/routes.rb
NewsPortal::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  ActiveAdmin.routes(self)
  devise_for :users
  match '/users/unsubscribe/:signature' => 'users#unsubscribe', as: 'unsubscribe', via: 'get'
  root 'posts#category'
  match '/about', to: 'static_pages#about', via: 'get'
  resources :posts do
    get '/category/:slug' => :category, on: :collection, as: 'category'
  end

  resources :subscriptions, only: [:index, :create, :destroy]
  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments]

end

app/views/layouts/_flash.html.slim
- flash.each do |key, value|
  = content_tag(:div, value, class: "alert alert-#{key}")

app/views/layouts/_footer.html.slim
footer.footer
  small
    a href="http://vk.com/george.belov" =' "George Belov"

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "NewsPortal", root_path, id: "logo"
      nav
        ul.nav.pull-right
          li= link_to "Home",    root_path
          li= link_to "About",   about_path
          li id="fat-menu" class="dropdown"
            a.dropdown-toggle data-toggle="dropdown" href="#"
              i.el-icon-th
              | Categories
              b.caret
            ul.dropdown-menu
              li
                = link_to "All posts", root_path
              li
                = link_to "Policy", category_posts_path('policy')
              li
                = link_to "Sport", category_posts_path('sport')
              li
                = link_to "Culture", category_posts_path('culture')
              li
                = link_to "Business", category_posts_path('business')
              li
                = link_to "Science", category_posts_path('science')
          - if user_signed_in?
            li
              = link_to "New post", new_post_path
            li
              = link_to "Subscriptions", subscriptions_path
            li id="fat-menu" class="dropdown"
              a.dropdown-toggle data-toggle="dropdown" href="#"
                i.icon-user
                = current_user.username
                b.caret
              ul.dropdown-menu
                li
                  = link_to "Sign out", destroy_user_session_path, method: :delete
          - else
            li
              =' link_to "Sign in", new_user_session_path
            li
              = link_to "Sign up", new_user_registration_path

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsPortal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">

  <div id="flash">
    <%= render :partial => 'layouts/flash' , :locals => { :flash => flash } %>
  </div>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>